/**
 *This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
 *Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
 */

package {
	
	import com.viddler.api.v2.client.utils.ReflectionToStringBuilderTest;
	
	import flash.display.Sprite;
	import com.viddler.api.v2.client.utils.XMLParserTest;
	
	
	public class FlexUnitCompilerApplication extends Sprite {
		private var com_viddler_api_v2_client_utils_XMLParserTest_obj:com.viddler.api.v2.client.utils.XMLParserTest;
		private var com_viddler_api_v2_client_utils_ReflectionToStringBuilderTest_obj:com.viddler.api.v2.client.utils.ReflectionToStringBuilderTest;
	}
}